#!/bin/bash

export DISPLAY=:0

xhost +local

docker run \
       -it \
       --rm \
       --runtime nvidia \
       --network host \
       --device /dev/video0:/dev/video0 \
       -e DISPLAY=$DISPLAY \
       -v /tmp/.X11-unix/:/tmp/.X11-unix \
       jetson-yolov5:latest python3 detect.py --source 0
